name: Teison EV Charger
version: "1.0"
slug: teison_ev_charger
description: Control Teison EV charger via cloud API and Home Assistant
startup: application
boot: auto
ingress: true
ingress_port: 5000
panel_icon: mdi:ev-station
options:
  username: ""
  password: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "homeassistant"
  mqtt_pass: ""
  device_index: 0
schema:
  username: str
  password: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  device_index: int
