name: "Teison EV Charger Control"
version: "1.0.7"
slug: "teison_ev_charger"
description: "Control a Teison EV Charger via cloud API"
startup: "application",
boot: "auto"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  username: ""
  password: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "homeassistant"
  device_index: 0
  access_token: ""
schema:
  username: "str"
  password: "str"
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_user: "str"
  mqtt_pass: "str"
  device_index: "int"
  access_token: "str"
ports:
  "5000/tcp": 5000
webui: "http://[HOST]:[PORT:5000]"
